name: Flutter CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.1'
        
    - name: Install dependencies
      working-directory: ./flutter_components_hub
      run: flutter pub get
      
    - name: Verify formatting
      working-directory: ./flutter_components_hub
      run: dart format --output=none --set-exit-if-changed .
      
    - name: Analyze project source
      working-directory: ./flutter_components_hub
      run: flutter analyze
      
    - name: Run tests
      working-directory: ./flutter_components_hub
      run: flutter test
      
  build-android:
    runs-on: ubuntu-latest
    needs: analyze-and-test
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.1'
        
    - name: Install dependencies
      working-directory: ./flutter_components_hub
      run: flutter pub get
      
    - name: Build APK
      working-directory: ./flutter_components_hub
      run: flutter build apk --debug
      
  build-web:
    runs-on: ubuntu-latest
    needs: analyze-and-test
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.1'
        
    - name: Install dependencies
      working-directory: ./flutter_components_hub
      run: flutter pub get
      
    - name: Build Web
      working-directory: ./flutter_components_hub
      run: flutter build web
      
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./flutter_components_hub/build/web